# Air configuration file for hot reloading
root = "."
tmp_dir = "tmp"

[build]
# Binary file yields from `cmd`
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ."
# Customize binary
full_bin = "./tmp/main"
# Watch these filename extensions
include_ext = ["go", "tpl", "tmpl", "html", "env"]
# Ignore these filename extensions or directories
exclude_dir = ["assets", "tmp", "vendor", ".git", "node_modules", "target"]
# Watch these directories if you specified
include_dir = []
# Exclude files
exclude_file = []
# This log file places in your tmp_dir
log = "air.log"
# It's not necessary to trigger build each time file changes if it's too frequent
delay = 1000 # ms
# Stop running old binary when build errors occur
stop_on_error = true
# Send interrupt signal before killing process (windows does not support this feature)
send_interrupt = false
# Kill process if you use this option
kill_delay = 500 # ms

[log]
# Show log time
time = false

[color]
# Customize each part's color
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
