name: Node.js CI

on:
  push:
    branches: [ main ] # Or your default branch
    paths:
      - 'src/main/node/**'
      - '.github/workflows/node-ci.yml'
  pull_request:
    branches: [ main ] # Or your default branch
    paths:
      - 'src/main/node/**'
      - '.github/workflows/node-ci.yml'

jobs:
  test_node:
    name: Test Node.js
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify a Node.js version, e.g., 16, 18, 20

      - name: Install dependencies
        working-directory: ./src/main/node
        run: npm install

      - name: Run Node.js tests
        working-directory: ./src/main/node
        run: npm test # This will run the script defined in package.json
